---

# Number found as /dev/video0
camera: 0

# Serial port in the arduino app, found in /dev; e.g. ttyACM1, or cu.usbmodem1201
arduino: cu.usbmodem1101

# Absolute path to where you want the output data to be stored
# Leave blank to export data to the directory containing config.yaml
output_folder: